export const MEMORY_COMMAND_SERVICE = Symbol('MEMORY_COMMAND_SERVICE');
export const IMAGE_MOOD_AGENT = Symbol('IMAGE_MOOD_AGENT');
export const MEMORY_IMAGE_STORAGE = Symbol('MEMORY_IMAGE_STORAGE');
export const MEMORY_REPOSITORY = Symbol('MEMORY_REPOSITORY');
