import { INameGenerator } from '../../user-core/output/name.generator';

export class NameGeneratorList implements INameGenerator {
  private readonly modifiers: string[] = [
    '무서운',
    '귀여운',
    '용감한',
    '조용한',
    '신나는',
    '빠른',
    '느긋한',
    '똑똑한',
    '엉뚱한',
    '화난',
    '친절한',
    '도도한',
    '장난기많은',
    '수줍은',
    '강력한',
    '포근한',
    '상쾌한',
    '눈부신',
    '배고픈',
    '행복한',
    '슬픈',
    '놀란',
    '멋진',
    '소심한',
    '도전적인',
    '우아한',
    '산만한',
    '차분한',
    '욕심쟁이',
    '신비로운',
    '지혜로운',
    '뚱뚱한',
    '날씬한',
    '피곤한',
    '활발한',
    '냉철한',
    '따뜻한',
    '달콤한',
    '짜증난',
    '느끼한',
    '유쾌한',
    '심각한',
    '단단한',
    '부드러운',
    '화려한',
    '소박한',
    '당당한',
    '어설픈',
    '솔직한',
    '비밀스러운',
  ];

  private readonly animals: string[] = [
    '사자',
    '고양이',
    '호랑이',
    '강아지',
    '토끼',
    '여우',
    '늑대',
    '곰',
    '판다',
    '코끼리',
    '기린',
    '얼룩말',
    '원숭이',
    '하마',
    '악어',
    '펭귄',
    '수달',
    '돌고래',
    '고래',
    '상어',
    '독수리',
    '부엉이',
    '참새',
    '비둘기',
    '공작',
    '까마귀',
    '다람쥐',
    '햄스터',
    '고슴도치',
    '너구리',
    '미어캣',
    '알파카',
    '낙타',
    '사슴',
    '순록',
    '양',
    '염소',
    '소',
    '돼지',
    '말',
    '치타',
    '표범',
    '재규어',
    '하이에나',
    '카멜레온',
    '도마뱀',
    '거북이',
    '개구리',
    '문어',
    '오징어',
  ];

  async generateName(): Promise<string> {
    const randomModifier =
      this.modifiers[Math.floor(Math.random() * this.modifiers.length)];
    const randomAnimal =
      this.animals[Math.floor(Math.random() * this.animals.length)];
    const randomNumber = Math.floor(Math.random() * 100) + 1;

    return await Promise.resolve(
      `${randomModifier} ${randomAnimal}${randomNumber}`,
    );
  }
}
